---
title: "DS 362 Homework 2"
format: 
  html:
    theme: pulse  
    toc: true
---

This is Homework Assignment 2 for DS 362. You can view the source code for this assignment on GitHub: [view the source code](https://github.com/jmgraham30/ds_362_assignments/blob/main/homework_02/index.qmd).

For your amusement: Knock knock. "Who's there?" Figs. "Figs who?" "Figs the doorbell. I've been knocking forever!"

## Problems

Many of the problems in this homework assignment are from the course text [An Introduction to Statistical Learning](https://www.statlearning.com/) which we will abbreviate as ISLR. [Access the book online here](https://hastie.su.domains/ISLR2/ISLRv2_corrected_June_2023.pdf).

Please complete and hand in this assignment as a Quarto notebook. 

### Problem 1

Please complete exercise 1 from section 2.4 on page 52 from the ISLR course text.


### Problem 2


Please complete exercise 4 from section 2.4 on page 53 from the ISLR course text.

### Problem 3


Please complete exercise 10 from section 2.4 on page 57 from the ISLR course text.


### Problem 4

Complete exercise 1 on pages 39 - 40 of the textbook Statistical Learning with Math and R by Joe Suzuki, available online through the Weinberg Library, [view the text](https://link-springer-com.ezp.scranton.edu/book/10.1007/978-981-15-7568-6). There is also a version of the text using Python instead of R, [view the Python version](https://link-springer-com.ezp.scranton.edu/book/10.1007/978-981-15-7877-9)
