---
title: "DS 362 Modeling Case Study 2"
format: 
  html:
    theme: pulse
---


For your amusement: Where do hamburgers like to dance? At a meatball! 

## Assignment Overview and Instructions

The goal of this modeling case study is for you to get hands-on experience in going through the steps of a machine learning problem from beginning to end with provided data. The case studies in this assignment will focus on hyperparameter tuning, fitting and comparing multiple models, and unsupervised methods that have been covered in class so far or are similar to those we have covered in class so far. 

For this assignment, you should create and work in an RStudio project named `case_study_2_lastname` where you will replace the `lastname` part with your last name. You should create either an appropriately names Quarto notebook or an appropriately names R script to save all you code in. Finally, you should maintain your project as a GitHub repository.


### Hyperparameter Tuning and Model Comparison Case Study



### Unsupervised Learning Case Study


